language: php

php:
  - 7.1.8

before_script: composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs --standard=PSR2

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false