version: "2"
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: gv-docker
    ports:
      - 8089:80
    volumes:
      - .:/var/www/gv
    environment:
      DB_HOST: mysql
      DB_DATABASE: gv
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: gv
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:4.0-alpine
    ports:
      - 16379:6379
