config:
  devmode: false
  mysql:
    host: mysql
    db_name: gv
    username: root
    password: root
  redis:
    host: redis
    port: 6379
    username:
    password:
  email:
    host: lala.example.com
    smtp_auth: true
    username:
    password:
    smtp_secure:
    port:
