dispatcher:
  classPath: Gvera\Helpers\events\
  objects:
    eventDispatcher:
      class: EventDispatcher
      singleton: true

services:
  classPath: Gvera\Services\
  objects:
    userService:
      class: UserService
      singleton: true

commands:
    classPath: Gvera\Commands\
    objects:
      loginCommand:
        class: LoginCommand
        arguments:
          "@userService"

listeners:



      
